/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jakos176.views;

import java.awt.Color;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author edu
 */
public class Table extends javax.swing.JFrame {

    private String actualTurn = "";
    private final String TURN_0 = "O";
    private final String TURN_X = "X";
    private boolean isWinner = false;

    public Table() {
        initComponents();
        this.jPanel1.setBackground(Color.WHITE);
        this.jPanel1.setLayout(null);
        this.setLayout(null);
        this.setLocationRelativeTo(null);
        this.jDialog1.setLocationRelativeTo(null);
        this.jDialog1.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        DialogLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Square1 = new javax.swing.JLabel();
        Square2 = new javax.swing.JLabel();
        Square3 = new javax.swing.JLabel();
        Square4 = new javax.swing.JLabel();
        Square5 = new javax.swing.JLabel();
        Square6 = new javax.swing.JLabel();
        Square7 = new javax.swing.JLabel();
        Square8 = new javax.swing.JLabel();
        Square9 = new javax.swing.JLabel();

        jDialog1.setAutoRequestFocus(false);
        jDialog1.setBackground(new java.awt.Color(204, 0, 204));
        jDialog1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialog1.setForeground(java.awt.Color.gray);
        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(150, 200));

        DialogLabel.setBackground(new java.awt.Color(255, 255, 255));
        DialogLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        DialogLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DialogLabel.setText("Ganaste");
        DialogLabel.setFocusable(false);
        DialogLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DialogLabel.setOpaque(true);
        DialogLabel.setPreferredSize(new java.awt.Dimension(100, 32));

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DialogLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DialogLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Square1.setBackground(new java.awt.Color(255, 255, 255));
        Square1.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        Square1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Square1.setToolTipText("");
        Square1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Square1.setOpaque(true);
        Square1.setPreferredSize(new java.awt.Dimension(50, 50));
        Square1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Square1MousePressed(evt);
            }
        });

        Square2.setBackground(new java.awt.Color(255, 255, 255));
        Square2.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        Square2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Square2.setToolTipText("");
        Square2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Square2.setOpaque(true);
        Square2.setPreferredSize(new java.awt.Dimension(50, 50));
        Square2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Square2MousePressed(evt);
            }
        });

        Square3.setBackground(new java.awt.Color(255, 255, 255));
        Square3.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        Square3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Square3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Square3.setOpaque(true);
        Square3.setPreferredSize(new java.awt.Dimension(50, 50));
        Square3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Square3MouseClicked(evt);
            }
        });

        Square4.setBackground(new java.awt.Color(255, 255, 255));
        Square4.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        Square4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Square4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Square4.setOpaque(true);
        Square4.setPreferredSize(new java.awt.Dimension(50, 50));
        Square4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Square4MouseClicked(evt);
            }
        });

        Square5.setBackground(new java.awt.Color(255, 255, 255));
        Square5.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        Square5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Square5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Square5.setOpaque(true);
        Square5.setPreferredSize(new java.awt.Dimension(50, 50));
        Square5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Square5MouseClicked(evt);
            }
        });

        Square6.setBackground(new java.awt.Color(255, 255, 255));
        Square6.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        Square6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Square6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Square6.setOpaque(true);
        Square6.setPreferredSize(new java.awt.Dimension(50, 50));
        Square6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Square6MouseClicked(evt);
            }
        });

        Square7.setBackground(new java.awt.Color(255, 255, 255));
        Square7.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        Square7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Square7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Square7.setOpaque(true);
        Square7.setPreferredSize(new java.awt.Dimension(50, 50));
        Square7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Square7MouseClicked(evt);
            }
        });

        Square8.setBackground(new java.awt.Color(255, 255, 255));
        Square8.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        Square8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Square8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Square8.setOpaque(true);
        Square8.setPreferredSize(new java.awt.Dimension(50, 50));
        Square8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Square8MouseClicked(evt);
            }
        });

        Square9.setBackground(new java.awt.Color(255, 255, 255));
        Square9.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        Square9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Square9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Square9.setOpaque(true);
        Square9.setPreferredSize(new java.awt.Dimension(50, 50));
        Square9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Square9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Square4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Square1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Square7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Square2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Square3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Square5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Square6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Square8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Square9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Square2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Square3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Square1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Square5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Square6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Square4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Square9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Square8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Square7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Square1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Square1MousePressed
        this.checkTurns(Square1);        // TODO add your handling code here:
    }//GEN-LAST:event_Square1MousePressed

    private void Square2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Square2MousePressed
        this.checkTurns(Square2);        // TODO add your handling code here:
    }//GEN-LAST:event_Square2MousePressed

    private void Square3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Square3MouseClicked
        this.checkTurns(Square3);        // TODO add your handling code here:
    }//GEN-LAST:event_Square3MouseClicked

    private void Square5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Square5MouseClicked
        this.checkTurns(Square5);        // TODO add your handling code here:
    }//GEN-LAST:event_Square5MouseClicked

    private void Square6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Square6MouseClicked
        this.checkTurns(Square6);        // TODO add your handling code here:
    }//GEN-LAST:event_Square6MouseClicked

    private void Square7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Square7MouseClicked
        this.checkTurns(Square7);        // TODO add your handling code here:
    }//GEN-LAST:event_Square7MouseClicked

    private void Square8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Square8MouseClicked
        this.checkTurns(Square8);        // TODO add your handling code here:
    }//GEN-LAST:event_Square8MouseClicked

    private void Square9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Square9MouseClicked
        this.checkTurns(Square9);        // TODO add your handling code here:
    }//GEN-LAST:event_Square9MouseClicked

    private void Square4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Square4MouseClicked
        this.checkTurns(Square4);        // TODO add your handling code here:
    }//GEN-LAST:event_Square4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    private void swapTurns() {
        this.actualTurn = this.actualTurn.equals(this.TURN_0) ? this.TURN_X : this.TURN_0;
    }

    private void checkTurns(JLabel label) {
        if (!this.isWinner) {
            if (label.getText().isEmpty()) {
                if (this.actualTurn.equals(this.TURN_0)) {
                    this.actualTurn = this.TURN_0;
                    label.setText(this.TURN_0);
                } else {
                    this.actualTurn = this.TURN_X;
                    label.setText(this.TURN_X);
                }
                this.checkWinner();
                this.swapTurns();
            }
        }
    }

    private void checkWinner() {
        if (this.isSameTextThanTurn(this.Square1, this.Square2, this.Square3)) {
            this.paintSquare(Square1, Square2, Square3);
        }
        else if (this.isSameTextThanTurn(this.Square1, this.Square4, this.Square7)) {
            this.paintSquare(Square1, Square4, Square7);
        } else if (this.isSameTextThanTurn(this.Square1, this.Square5, this.Square9)) {
            this.paintSquare(Square1, Square5, Square9);
        } else if (this.isSameTextThanTurn(this.Square4, this.Square5, this.Square6)) {
            this.paintSquare(Square4, Square5, Square6);
        } else if (this.isSameTextThanTurn(this.Square7, this.Square8, this.Square9)) {
            this.paintSquare(Square7, Square8, Square9);
        } else if (this.isSameTextThanTurn(this.Square7, this.Square5, this.Square3)) {
            this.paintSquare(Square7, Square5, Square3);
        } else if (this.isSameTextThanTurn(this.Square2, this.Square5, this.Square8)) {
            this.paintSquare(Square2, Square5, Square8);          
        } else if (this.isSameTextThanTurn(this.Square3, this.Square6, this.Square9)) {
            this.paintSquare(Square3, Square6, Square9);
        }
    }

    private void paintSquare(JLabel label1, JLabel label2, JLabel label3) {
        List<JLabel> labels = List.of(label1, label2, label3);
        labels.forEach(label -> label.setBackground(Color.GREEN));
        this.isWinner = true;
        this.jDialog1.setVisible(true);
    }

    private boolean isSameTextThanTurn(JLabel label1, JLabel label2, JLabel label3) {
        List<JLabel> labels = List.of(label1, label2, label3);
        return labels.stream().allMatch(label -> label.getText().equals(this.actualTurn));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DialogLabel;
    private javax.swing.JLabel Square1;
    private javax.swing.JLabel Square2;
    private javax.swing.JLabel Square3;
    private javax.swing.JLabel Square4;
    private javax.swing.JLabel Square5;
    private javax.swing.JLabel Square6;
    private javax.swing.JLabel Square7;
    private javax.swing.JLabel Square8;
    private javax.swing.JLabel Square9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
